### ISSUE TITLE
isn't embedding the rest api key in the application a security risk?

### ISSUE THREAD

**Issue by koenpunt** [baspellis/WCParsePush#1]

**Comment by baspellis** [comment]
In the Parse Push Settings the following is written for the client push setting:

> Enable client push to allow push notifications to be sent by using the public client keys. This is useful during development, but we recommend disabling it on production apps.

However for people who do want to use the client key instead of the REST API key I will  I will add support to use the client key. Thanks for your feedback.

**Comment by koenpunt** [comment]
Client push is something else than using the client key. A client key can be used to register a client, and execute client scoped actions, hence the name. With the REST key, people have generic access to all objects, and exposing this key can result in serious harm to your Parse application.

See my PR for a solution: #2

**Comment by baspellis** [comment]
Aight, thanks for that clarification. I've implemented your PR.
